### ISSUE TITLE
fix 500 error on bad requests

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#1]
The following HTTP GET request returns 500:

https://oscar.wmo.int/surface/rest/api/stations/approvedStations/wmoIds

The WADL in https://oscardevt.meteoswiss.ch/surface/rest/api?_wadl says to include the `pageSize`, `q`, and `page` parameters are part of the request.

For missing parameters, the HTTP response should be 400, not 500

**Comment by joergklausen** [comment]
The acceptable endpoints are listed in the wadl, e.g., .../wigosIds, .../gawIds.
