### ISSUE TITLE
date representations

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#14]
Examples like https://oscar.wmo.int/surface/rest/api/contacts/contact/1156 provide the the following date information:

```json
"lastModifiedOn": 1203634800000
```

It would be valuable to have dates/datetimes represented as RFC3339 or ISO8601.

**Comment by joergklausen** [comment]
issue handed over to https://ext-bug.eurodyn.com/show_bug.cgi?id=11715
