### ISSUE TITLE
get station in WIGOS WMDR XML representation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#16]
Does the API provide this capability?  Currently JSON is provided.

Example: https://oscar.wmo.int/surface/rest/api/stations/station/9565/stationReport

**Comment by luciacap** [comment]
oscar.wmo.int/surface/rest/api/wmd/download/[WIGOS ID]
example: oscar.wmo.int/surface/rest/api/wmd/download/0-20000-0-06679

**Comment by tomkralidis** [comment]
Thanks @luciacap. Implemented in pyoscar.
