### ISSUE TITLE
wmdr:territoryNameValidPeriod should be optional

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#17]
In the WMDR XSD 1.0RC7, `wmdr:ObservingFacility/wmdr:territoryNameValidPeriod` is documented as follows:

> Specifies at least the begin date of the indicated territoryName. If omitted, the dateEstablished of the facility will be assumed.

However, the element is listed as required (should be optional).

**Comment by luciacap** [comment]
Fixed in Version 1.0RC8
