### ISSUE TITLE
wmdr:territoryName cardinality

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#18]
In the WMDR XSD 1.0RC7, `wmdr:ObservingFacility/wmdr:territoryName` has a single cardinality (along with `wmdr:ObservingFacility/wmdr:territoryNameValidPeriod`).  Stations whose jurisdiction changes over time require additional `wmdr:ObservingFacility` elements to be defined, or additional WMDR instance documents.

To better represent history/changes over time in thihs context, it is recommendation is to define something like `wmdr:territory` (1..*) with `wmdr:name` (required 1..1) and `wmdr:validPeriod` (optional 0..1)

**Comment by luciacap** [comment]
Fixed in Version 1.0RC8
