### ISSUE TITLE
provide default response on station listing pages

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#2]
The following HTTP GET request returns 500 because of missing parameters:

https://oscar.wmo.int/surface/rest/api/stations/approvedStations/wmoIds

(note the 500 error problem is issued in #1)

The WADL in https://oscardevt.meteoswiss.ch/surface/rest/api?_wadl says to include the `pageSize`, `q`, and `page` parameters are part of the request.

REST APIs/services out there usually don't require things like pageSize/etc. on a default "show me everything" type request.  The system typically has a default "maxsize" type value set at the server level.  So a request like the above with no params would return a number of records as delegated by the server.  If the user specifies `pageSize`, etc. explicity, then the API would obey that value.

**Comment by joergklausen** [comment]
https://oscar.wmo.int/surface/rest/api/stations/approvedStations/wigosIds works without problems, pageSize, q, page parameters are not required.
