### ISSUE TITLE
wmdr:reportingStatus and wmdr:programAffiliation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#20]
cc @acapparelli

Where can one model `wmdr:reportingStatus` and `wmdr:programAffiliation` (which were last seen in `wmdr:ObservingFacility` in 1.0RC4)?

**Comment by luciacap** [comment]
In Version 1.0RC8 wmdr:reportingStatus and wmdr:programAffiliation are again available under ObservingFacility/programAffiliation/ProgramAffiliation
