### ISSUE TITLE
Schema does not include an element for the geospatial reference system

### ISSUE THREAD

**Issue by luciacap** [wmo-cop/wmo-oscar#21]
Schema does not include an element for the coordinates reference System (WMDS element 3-07). Consider for Schema Version 2.0

**Comment by joergklausen** [comment]
This is now included in the EA model for the next version of the XSD (publication date unknown)

			<xs:element name="coordinateReferenceSystem" type="gml:ReferenceType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:appinfo>
				<gmlexr:targetCodeList>CoordinateReferenceSystemType</gmlexr:targetCodeList>
					</xs:appinfo>
				</xs:annotation>
			</xs:element>
