### ISSUE TITLE
provide OpenAPI definition of API capabilities

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#3]
API capabilities are put advertised in https://oscardevt.meteoswiss.ch/surface/rest/api?_wadl

The WADL is cumbersome to interpret.  Are there plans for supporting OpenAPI / Swagger?

**Comment by joergklausen** [comment]
Request acknowledged and requirements specification has been updated to include this as a possible future improvement, pending funding.
