### ISSUE TITLE
Treatment of supervising organization vs station contacts in OSCAR/Surface vs WMDS vs WMDR

### ISSUE THREAD

**Issue by joergklausen** [wmo-cop/wmo-oscar#32]
- WMDS
Element 9-01 is supervising *organization* without specific cardinality
- WMDR
ObservingFacility\responsibleParty is of type RepsonsibleParty which is modeled using CI_ResponsibleParty and has cardinality  [1..*]. CI_RespojnsibleParty allows specification of individual Name, etc
- OSCAR/Surface
The element is interpreted as WMDS element 9-01, and only the *organization* is extracted. Cardinality [1..1] is imposed at any one time.
--> Need to agree on cardinality and range of elements (only organization, or full contact) that can be expressed.

**Comment by tomkralidis** [comment]
Moved to https://github.com/wmo-im/wmdr/issues/18
