### ISSUE TITLE
Include Time Zone information in Schedule elements wmdr:hour, wmdr:minute

### ISSUE THREAD

**Issue by luciacap** [wmo-cop/wmo-oscar#39]
As of release 1.0RC9 schedule elements wmdr:hour and wmdr:minute are defined as numbers. Users cannot indicate if the provided time refers to local time or UTC nor it is documented what it should be used. This information is also relevant to count the number of expected observations for the WDQMS interface.

**Comment by tomkralidis** [comment]
Moved to https://github.com/wmo-im/wmdr/issues/23
