### ISSUE TITLE
Test environment down?

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#4]
Trying to access https://oscardevt.meteoswiss.ch/surface/index.html#/m2m results in a connection error.

**Comment by luciacap** [comment]
The server was rebooted 5 days ago for a patch installation. After that our IT team didn't notice anything wrong.  The installation of a service realese that Jörg mentioned had no effects on the API installation: it was performed on another environemnt and at a different time. 
Please let us know if this happens again.

**Comment by tomkralidis** [comment]
Thanks @luciacap. Confirmed server available now.
