### ISSUE TITLE
OSCAR 500 error when viewing station page

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#40]
Per subject.  URLs like https://gawsis.meteoswiss.ch/GAWSIS/index.html#/search/station/stationReportDetails/0-20008-0-DAV return 500.  We are linking from WMO WOUDC with this URL pattern and users are encountering issues in production. Please advise.

**Comment by luciacap** [comment]
The application is running again. We are currently investigating the issue.

**Comment by joergklausen** [comment]
resolved
