### ISSUE TITLE
code tables

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#6]
Many WMDR elements refer to code tables (for example, `wmdr:territoryName`).  Where can one access the code table defs to accurately encode codelist values in WMDR?

**Comment by luciacap** [comment]
Code tables entries and definitions are available under http://test.wmocodes.info/wmdr (in the future under http://codes.wmo.int/wmdr).

**Comment by luciacap** [comment]
and  https://drive.google.com/drive/folders/1nnf0m6Iux_9MPJyPm1yAq2qWwxeI8fCp?usp=sharing
