### ISSUE TITLE
query results should have summaries outside list of results

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#7]
When querying the API with `https://oscardevt.meteoswiss.ch//surface/rest/api/stations/approvedStations/wmoIds?q=&page=1&pageSize=10`, the response is as follows:

```json
[
  {
    "total": "14433",
    "id": "32441",
    "text": "0-00686-38009-0C"
  },
  {
    "id": "31569",
    "text": "0-20000-0-00927"
  },
  {
    "id": "1044",
    "text": "0-20000-0-01001"
  },
  {
    "id": "1045",
    "text": "0-20000-0-01002"
  },
  {
    "id": "1046",
    "text": "0-20000-0-01003"
  }
]
```

Why is the `total` summary property part of the first actual result?  Summary values should be parallel to the list of result objects.

**Comment by joergklausen** [comment]
Acknowledged, bug reported, issue closed.

**Comment by joergklausen** [comment]
Issue closed but tracked in application issue tracker.
