### ISSUE TITLE
API search by country

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#8]
Is there an example of how to query the API to find stations by a given country name/code?

**Comment by luciacap** [comment]
below an example for using cURL command in a CLI for the current application.
Replace the "78" (Greece) with the T_GO_TERRITORY_REF.TERRITORY_ID of your choice.

curl 'https://oscar.wmo.int/surface//rest/api/search/stationSearch' -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"operation":"AND","nrt":"false","quickSearch":false,"wmoRaOrCountryId":"C-78"}'

Country IDs can be retrieved with the call:
https://oscar.wmo.int/surface/rest/api/referenceData/list/TerritoryRef/1 

For the next Release of the productive application (R1.2.3 - no M2M) currently on DEPL environment and to be deployed end of February, there will be a more user-friendly API available. You will be able to get a list of stations in a country with the following call:

https://oscardepl.wmo.int/surface/rest/api/search/station?territoryName=GRC
The notation used for the TerritoryName (GRC in this case) is the WMO_306_CD available in the code registry.

This call will be also available for the productive M2M release but not earlier than the end of May.
