### ISSUE TITLE
programAffiliation codes appear incomplete

### ISSUE THREAD

**Issue by tomkralidis** [wmo-cop/wmo-oscar#9]
http://test.wmocodes.info/wmdr/ProgramAffiliation shows 19 codes in alphabetical order which are cut off at g.  Is this the complete list?

**Comment by luciacap** [comment]
As mentioned in the M2M Webex in December not all code tables are already available on the code registry. This is why we uploaded missing code tables on the following google drive:
https://drive.google.com/drive/folders/1nnf0m6Iux_9MPJyPm1yAq2qWwxeI8fCp?usp=sharing
There is also an overview of all OSCAR code tables and their current location: https://docs.google.com/document/d/1rbCY6IfCcp2-Djt4548TPt__1eZJwpEj2A3w0f7Vi94/edit

**Comment by tomkralidis** [comment]
Should we keep this issue open until all the codes are available on the registry?

**Comment by joergklausen** [comment]
All work on code lists tracked on https://github.com/wmo-im/wmdr.
